[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Zehs"
name = "TwitchChatAPI"
description = "Add Twitch chat integration to your Unity game mods! Subscribe to events like Messages, Cheers, Subs, and Raids. No Twitch authentication or connections required."
websiteUrl = "https://github.com/ZehsTeam/TwitchChatAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/TwitchChatAPI/release/TwitchChatAPI.dll"
target = "plugins/"

[[build.copy]]
source = "../../artifacts/bin/TwitchChatAPI.Deprecated/release/com.github.zehsteam.TwitchChatAPI.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE.txt"
target = "/"

[publish]
communities = [ "lethal-company", "repo", ]
[publish.categories]
lethal-company = [ "mods", "libraries", "misc", "client-side", ]
repo = [ "mods", "libraries", "misc", "client-side", ]
